/* eslint-disable @next/next/no-img-element */
"use client";
import {useState} from "react";
export type TuriniStyle={category:"none"|"hats"|"glasses"|"neck"|"bags";item:string;background:string};
export const DEFAULT_TURINI_STYLE:TuriniStyle={category:"none",item:"",background:""};
const ITEMS={hats:["green_cap","yellow_bucket","explorer_hat","red_beanie","graduation_cap","gold_crown","straw_hat","chef_hat","wizard_hat"],glasses:["green_round","black_square","gold_round","heart_sunglasses","blue_sport","star_glasses","red_reading","monocle","safety_goggles"],neck:["green_bow","red_tie","blue_scarf","yellow_bandana","pearl_necklace","gold_medal","camera","flower_lei","white_green_collar"],bags:["green_original","yellow_giraffe","navy_school","red_hiking","tan_explorer","purple_star","mint_bubble","black_business","pink_heart"]} as const;
const LABELS:Record<string,string>={green_cap:"초록 모자",yellow_bucket:"노랑 버킷햇",explorer_hat:"탐험 모자",red_beanie:"빨강 비니",graduation_cap:"학사모",gold_crown:"황금 왕관",straw_hat:"밀짚모자",chef_hat:"요리사 모자",wizard_hat:"마법사 모자",green_round:"초록 안경",black_square:"검정 안경",gold_round:"금테 안경",heart_sunglasses:"하트 선글라스",blue_sport:"스포츠 안경",star_glasses:"별 안경",red_reading:"빨강 안경",monocle:"외알 안경",safety_goggles:"보호 안경",green_bow:"초록 리본",red_tie:"빨강 넥타이",blue_scarf:"파랑 목도리",yellow_bandana:"노랑 반다나",pearl_necklace:"진주 목걸이",gold_medal:"금메달",camera:"카메라",flower_lei:"꽃목걸이",white_green_collar:"초록 칼라",green_original:"나뭇잎 가방",yellow_giraffe:"기린 가방",navy_school:"네이비 가방",red_hiking:"등산 가방",tan_explorer:"탐험 가방",purple_star:"보라 별 가방",mint_bubble:"민트 가방",black_business:"검정 가방",pink_heart:"분홍 하트 가방"};
const BACKGROUNDS=["","study_room_day","finance_city","forest_class","goal_room_night"] as const;
const BG:Record<string,string>={"":"배경 없음",study_room_day:"낮 공부방",finance_city:"금융 도시",forest_class:"숲속 교실",goal_room_night:"밤 목표방"};
export function normalizeTuriniStyle(value:unknown):TuriniStyle{if(!value||typeof value!=="object")return DEFAULT_TURINI_STYLE;const s=value as Partial<TuriniStyle>;const category=s.category&&["none","hats","glasses","neck","bags"].includes(s.category)?s.category:"none";const available=category==="none"?[]:ITEMS[category];const item=typeof s.item==="string"&&available.includes(s.item as never)?s.item:"";const background=typeof s.background==="string"&&BACKGROUNDS.includes(s.background as never)?s.background:"";return {category:item?category:"none",item,background};}
const imageFor=(s:TuriniStyle)=>s.category==="none"||!s.item?"/assets/turini/character/base/turini-base-no-backpack.png":`/assets/turini/equipped/${s.category}/${s.item}-worn.png`;
export function StyledTurini({style,className="",label="내가 꾸민 투리니"}:{style:TuriniStyle;className?:string;label?:string}){return <span className={`styled-turini ${style.category==="bags"?"bag-view":""} ${className}`.trim()}>{style.background?<img className="styled-turini__background" src={`/assets/turini/backgrounds/${style.background}.png`} alt=""/>:null}<img className="styled-turini__character" src={imageFor(style)} alt={label}/></span>}
export function TuriniStyleCustomizer({value,onChange}:{value:TuriniStyle;onChange:(v:TuriniStyle)=>void}){const [tab,setTab]=useState<"hats"|"glasses"|"neck"|"bags"|"background">(value.category==="none"?"hats":value.category);const tabs=[{key:"hats",label:"모자"},{key:"glasses",label:"안경"},{key:"neck",label:"목"},{key:"bags",label:"가방"},{key:"background",label:"배경"}] as const;const list=tab==="background"?[]:ITEMS[tab];return <section className="avatar-customizer card-block"><div className="avatar-heading"><div><p className="eyebrow">MY TURINI</p><h2>나만의 투리니 스타일</h2><p>실제 착용 이미지로 자연스럽게 보여요.</p></div><StyledTurini style={value} className="avatar-preview"/></div><p className="avatar-policy">현재 자산은 여러 액세서리를 겹치면 어색해져 대표 스타일 한 개와 배경을 조합해요. 가방은 3/4 방향으로 확인할 수 있어요.</p><div className="avatar-tabs" role="tablist">{tabs.map(t=><button type="button" role="tab" aria-selected={tab===t.key} className={tab===t.key?"active":""} key={t.key} onClick={()=>setTab(t.key)}>{t.label}</button>)}</div>{tab==="background"?<div className="avatar-items backgrounds">{BACKGROUNDS.map(b=><button type="button" key={b||"none"} className={value.background===b?"selected":""} onClick={()=>onChange({...value,background:b})}>{b?<img src={`/assets/turini/backgrounds/${b}.png`} alt=""/>:<span>없음</span>}<b>{BG[b]}</b></button>)}</div>:<div className="avatar-items"><button type="button" className={value.category==="none"?"selected":""} onClick={()=>onChange({...value,category:"none",item:""})}><span>기본</span><b>기본 모습</b></button>{list.map(item=><button type="button" key={item} className={value.category===tab&&value.item===item?"selected":""} onClick={()=>onChange({...value,category:tab,item})}><img src={`/assets/turini/equipped/${tab}/${item}-worn.png`} alt=""/><b>{LABELS[item]}</b></button>)}</div>}</section>}
